"""Источники-«статусники» (M8+, D-016).

Каталог источников проекта: новостные RSS/Atom-ленты и отдельно —
operational status endpoints, которые не являются новостями.

Почему два вида:

* ``kind="news"`` — редакционные ленты. Только они попадают в
  ``config.SOURCES`` и участвуют в ``collect``/``run``/``doctor``.
* ``kind="status"`` — лента инцидентов status-страницы
  (``status.<vendor>/history.rss``, ``*.statuspage.io``). Содержимое — «все
  системы работают» / «инцидент закрыт», то есть не новости: такие записи
  объявлены в каталоге, но не собираются и не публикуются.

Данные каталога можно полностью заменить импортом из таблицы:

```bash
python -m telecom_news sources import --csv sources.csv --dry-run
python -m telecom_news sources import --csv sources.csv
python -m telecom_news sources --kind all        # что получилось
python -m telecom_news sources verify            # живая проверка эндпоинтов
```

Импорт читает все листы книги, классифицирует строки по колонке «Тип источника»
и URL (``Operational status / incidents`` и ``status.*/history.rss`` → status;
MIME не является решающим, потому что у status-эндпоинтов он указан как
``application/rss+xml``), а строки со статусом «исключён / не вошёл / 404 /
timeout» в каталог не попадают.
"""

from __future__ import annotations

from dataclasses import dataclass

KIND_NEWS = "news"
KIND_STATUS = "status"
KINDS = (KIND_NEWS, KIND_STATUS)

GRADES = ("A+", "A", "B+", "B")


@dataclass(frozen=True)
class CatalogEntry:
    """Одна запись каталога источников.

    ``id`` должен быть уникален среди всех источников (он же ключ в
    ``config.SOURCES`` для news). ``gate`` — политика релевантности:
    ``"strict"`` (детерминированный keyword-guard, D-011) или ``"llm"``
    (сразу модель, D-012) для узких лент.
    """

    id: str
    url: str
    kind: str = KIND_NEWS
    language: str = "en"
    grade: str = "A"
    topic: str = ""
    gate: str = "strict"
    enabled: bool = True
    verified: str = ""
    note: str = ""


# generated from docs/sms_messaging_rss_100_unique_sources_verified_2026-09-11.xlsx on 2026-09-11 by
# `python -m telecom_news sources import`
CATALOG: tuple[CatalogEntry, ...] = (
    CatalogEntry(
        id="2600hz",
        url="https://blog.2600hz.com/rss.xml",
        kind="news",
        language="en",
        grade="A+",
        topic="CPaaS; SMS; 10DLC; telecom APIs; cloud communications",
        gate="strict",
        enabled=True,
        verified="2026-09-11",
        note="user verified: CPaaS; SMS; 10DLC; telecom APIs; cloud communications",
    ),
    CatalogEntry(
        id="acefone",
        url="https://www.acefone.com/blog/feed/",
        kind="news",
        language="en",
        grade="A",
        topic="SMS/business communications; cloud telephony; APIs; contact center",
        gate="strict",
        enabled=True,
        verified="2026-09-11",
        note="user verified: SMS/business communications; cloud telephony; APIs; contact center",
    ),
    CatalogEntry(
        id="alertify",
        url="https://alertify.eu/feed/?x=1",
        kind="news",
        language="en",
        grade="A",
        topic="mobile operators; roaming; messaging; telecom services; deals",
        gate="strict",
        enabled=True,
        verified="2026-09-11",
        note="user verified: mobile operators; roaming; messaging; telecom services; deals",
    ),
    CatalogEntry(
        id="betwext",
        url="https://www.betwext.com/feed/",
        kind="news",
        language="en",
        grade="A+",
        topic="SMS marketing; text campaigns; messaging use cases",
        gate="strict",
        enabled=True,
        verified="2026-09-11",
        note="user verified: SMS marketing; text campaigns; messaging use cases",
    ),
    CatalogEntry(
        id="beyond-telecom-law-blog",
        url="https://www.beyondtelecomlawblog.com/feed/",
        kind="news",
        language="en",
        grade="A",
        topic="telecom regulation; messaging compliance; carriers; numbering",
        gate="strict",
        enabled=True,
        verified="2026-09-11",
        note="user verified: telecom regulation; messaging compliance; carriers; numbering",
    ),
    CatalogEntry(
        id="biocatch",
        url="https://www.biocatch.com/blog/rss.xml",
        kind="news",
        language="en",
        grade="A",
        topic="OTP/social engineering fraud; account takeover; fraud prevention",
        gate="strict",
        enabled=True,
        verified="2026-09-11",
        note="user verified: OTP/social engineering fraud; account takeover; fraud prevention",
    ),
    CatalogEntry(
        id="circleid-telecom",
        url="https://circleid.com/rss/topics/telecom",
        kind="news",
        language="en",
        grade="A",
        topic="telecom policy; carriers; numbering; regulation; infrastructure",
        gate="strict",
        enabled=True,
        verified="2026-09-11",
        note="user verified: telecom policy; carriers; numbering; regulation; infrastructure",
    ),
    CatalogEntry(
        id="comm-law-center",
        url="https://www.commlawcenter.com/feed/",
        kind="news",
        language="en",
        grade="A",
        topic="FCC; TCPA; telecom compliance; calling/texting regulation",
        gate="strict",
        enabled=True,
        verified="2026-09-11",
        note="user verified: FCC; TCPA; telecom compliance; calling/texting regulation",
    ),
    CatalogEntry(
        id="commlawblog",
        url="https://www.commlawblog.com/feed/",
        kind="news",
        language="en",
        grade="A",
        topic="FCC; telecom regulation; robocalls; messaging compliance",
        gate="strict",
        enabled=True,
        verified="2026-09-11",
        note="user verified: FCC; telecom regulation; robocalls; messaging compliance",
    ),
    CatalogEntry(
        id="deutsche-telekom-blog",
        url="https://www.telekom.com/service/rss/1714/feed.rss",
        kind="news",
        language="en",
        grade="A",
        topic="operator products; mobile communications; security; partnerships",
        gate="strict",
        enabled=True,
        verified="2026-09-11",
        note="user verified: operator products; mobile communications; security; partnerships",
    ),
    CatalogEntry(
        id="dotdigital",
        url="https://dotdigital.com/feed/",
        kind="news",
        language="en",
        grade="A",
        topic="SMS; omnichannel messaging; customer communications; integrations",
        gate="strict",
        enabled=True,
        verified="2026-09-11",
        note="user verified: SMS; omnichannel messaging; customer communications; integrations",
    ),
    CatalogEntry(
        id="firetext",
        url="https://www.firetext.co.uk/blog/feed/",
        kind="news",
        language="en",
        grade="A+",
        topic="business SMS; SMS API; sender IDs; delivery; compliance",
        gate="strict",
        enabled=True,
        verified="2026-09-11",
        note="user verified: business SMS; SMS API; sender IDs; delivery; compliance",
    ),
    CatalogEntry(
        id="habr-informatsionnaya-bezopasnost-novosti",
        url="https://habr.com/ru/rss/hubs/infosecurity/news/?fl=ru",
        kind="news",
        language="ru",
        grade="A",
        topic="SMS fraud; OTP; phishing; mobile security; anti-fraud",
        gate="strict",
        enabled=True,
        verified="2026-09-11",
        note="user verified: SMS fraud; OTP; phishing; mobile security; anti-fraud",
    ),
    CatalogEntry(
        id="habr-informatsionnaya-bezopasnost-stati",
        url="https://habr.com/ru/rss/hubs/infosecurity/articles/?fl=ru",
        kind="news",
        language="ru",
        grade="A",
        topic="fraud techniques; mobile/SMS security; authentication",
        gate="strict",
        enabled=True,
        verified="2026-09-11",
        note="user verified: fraud techniques; mobile/SMS security; authentication",
    ),
    CatalogEntry(
        id="habr-sotovaya-svyaz-stati",
        url="https://habr.com/ru/rss/hubs/cellular/articles/?fl=ru",
        kind="news",
        language="ru",
        grade="A+",
        topic="сотовые сети; SMS; signaling; carriers; mobile core",
        gate="strict",
        enabled=True,
        verified="2026-09-11",
        note="user verified: сотовые сети; SMS; signaling; carriers; mobile core",
    ),
    CatalogEntry(
        id="habr-zakonodatelstvo-v-it-novosti",
        url="https://habr.com/ru/rss/hubs/business-laws/news/?fl=ru",
        kind="news",
        language="ru",
        grade="A",
        topic="регуляторные изменения; telecom; communications",
        gate="strict",
        enabled=True,
        verified="2026-09-11",
        note="user verified: регуляторные изменения; telecom; communications",
    ),
    CatalogEntry(
        id="habr-zakonodatelstvo-v-it-stati",
        url="https://habr.com/ru/rss/hubs/business-laws/articles/?fl=ru",
        kind="news",
        language="ru",
        grade="A",
        topic="законы; telecom regulation; персональные данные; рассылки",
        gate="strict",
        enabled=True,
        verified="2026-09-11",
        note="user verified: законы; telecom regulation; персональные данные; рассылки",
    ),
    CatalogEntry(
        id="local-text-marketers",
        url="https://localtextmarketers.com/feed/",
        kind="news",
        language="en",
        grade="A+",
        topic="SMS marketing; business texting; campaigns",
        gate="strict",
        enabled=True,
        verified="2026-09-11",
        note="user verified: SMS marketing; business texting; campaigns",
    ),
    CatalogEntry(
        id="mobile-europe",
        url="https://www.mobileeurope.co.uk/feed/",
        kind="news",
        language="en",
        grade="A",
        topic="MNOs; mobile infrastructure; APIs; security; partnerships",
        gate="strict",
        enabled=True,
        verified="2026-09-11",
        note="user verified: MNOs; mobile infrastructure; APIs; security; partnerships",
    ),
    CatalogEntry(
        id="mobilehigh5",
        url="https://www.mobilehigh5.com/feed/",
        kind="news",
        language="en",
        grade="A+",
        topic="SMS marketing; mobile messaging; customer engagement",
        gate="strict",
        enabled=True,
        verified="2026-09-11",
        note="user verified: SMS marketing; mobile messaging; customer engagement",
    ),
    CatalogEntry(
        id="mobileum-blog",
        url="https://blog.mobileum.com/rss.xml",
        kind="news",
        language="en",
        grade="A+",
        topic="A2P SMS; SMS firewall; grey routes; fraud; signaling; monetization",
        gate="strict",
        enabled=True,
        verified="2026-09-11",
        note="user verified: A2P SMS; SMS firewall; grey routes; fraud; signaling; monetization",
    ),
    CatalogEntry(
        id="moengage",
        url="https://www.moengage.com/feed/",
        kind="news",
        language="en",
        grade="A",
        topic="SMS; omnichannel messaging; WhatsApp; push; customer engagement",
        gate="strict",
        enabled=True,
        verified="2026-09-11",
        note="user verified: SMS; omnichannel messaging; WhatsApp; push; customer engagement",
    ),
    CatalogEntry(
        id="optiva",
        url="https://www.optiva.com/blog-feed.xml",
        kind="news",
        language="en",
        grade="A",
        topic="BSS; charging; telco monetization; operator services; partnerships",
        gate="strict",
        enabled=True,
        verified="2026-09-11",
        note="user verified: BSS; charging; telco monetization; operator services; partnerships",
    ),
    CatalogEntry(
        id="rcr-wireless-news",
        url="https://www.rcrwireless.com/feed",
        kind="news",
        language="en",
        grade="A",
        topic="mobile operators; telecom; messaging; 5G; carrier business",
        gate="strict",
        enabled=True,
        verified="2026-09-11",
        note="user verified: mobile operators; telecom; messaging; 5G; carrier business",
    ),
    CatalogEntry(
        id="sentext-solutions",
        url="https://www.sentextsolutions.com/feed/",
        kind="news",
        language="en",
        grade="A+",
        topic="business texting; SMS campaigns; customer messaging",
        gate="strict",
        enabled=True,
        verified="2026-09-11",
        note="user verified: business texting; SMS campaigns; customer messaging",
    ),
    CatalogEntry(
        id="seon",
        url="https://seon.io/resources/feed/",
        kind="news",
        language="en",
        grade="A",
        topic="SMS/OTP fraud; account takeover; fraud detection; anti-fraud",
        gate="strict",
        enabled=True,
        verified="2026-09-11",
        note="user verified: SMS/OTP fraud; account takeover; fraud detection; anti-fraud",
    ),
    CatalogEntry(
        id="sift",
        url="https://sift.com/blog/feed/",
        kind="news",
        language="en",
        grade="A",
        topic="account takeover; authentication fraud; digital fraud; anti-abuse",
        gate="strict",
        enabled=True,
        verified="2026-09-11",
        note="user verified: account takeover; authentication fraud; digital fraud; anti-abuse",
    ),
    CatalogEntry(
        id="simpletexting-blog",
        url="https://simpletexting.com/feed/",
        kind="news",
        language="en",
        grade="A+",
        topic="business SMS; MMS; 10DLC; carrier rules; compliance",
        gate="strict",
        enabled=True,
        verified="2026-09-11",
        note="user verified: business SMS; MMS; 10DLC; carrier rules; compliance",
    ),
    CatalogEntry(
        id="slicktext",
        url="https://www.slicktext.com/blog/feed/",
        kind="news",
        language="en",
        grade="A+",
        topic="business SMS; text marketing; compliance; campaigns",
        gate="strict",
        enabled=True,
        verified="2026-09-11",
        note="user verified: business SMS; text marketing; compliance; campaigns",
    ),
    CatalogEntry(
        id="tatango",
        url="https://www.tatango.com/feed/",
        kind="news",
        language="en",
        grade="A+",
        topic="SMS marketing; A2P; short codes; 10DLC; compliance",
        gate="strict",
        enabled=True,
        verified="2026-09-11",
        note="user verified: SMS marketing; A2P; short codes; 10DLC; compliance",
    ),
    CatalogEntry(
        id="telappliant",
        url="https://telappliant.com/feed/",
        kind="news",
        language="en",
        grade="A",
        topic="business messaging; cloud communications; telecom services",
        gate="strict",
        enabled=True,
        verified="2026-09-11",
        note="user verified: business messaging; cloud communications; telecom services",
    ),
    CatalogEntry(
        id="telecommunications-industry-association-tia",
        url="https://tiaonline.org/feed/",
        kind="news",
        language="en",
        grade="A",
        topic="telecom standards; policy; carriers; network security; ecosystem",
        gate="strict",
        enabled=True,
        verified="2026-09-11",
        note="user verified: telecom standards; policy; carriers; network security; ecosystem",
    ),
    CatalogEntry(
        id="teleforwarding",
        url="https://www.teleforwarding.com/feed/",
        kind="news",
        language="en",
        grade="A",
        topic="messaging; virtual numbers; voice/SMS; international telecom",
        gate="strict",
        enabled=True,
        verified="2026-09-11",
        note="user verified: messaging; virtual numbers; voice/SMS; international telecom",
    ),
    CatalogEntry(
        id="text-marketer",
        url="https://www.textmarketer.co.uk/feed/",
        kind="news",
        language="en",
        grade="A+",
        topic="bulk SMS; SMS gateway; business messaging; regulation",
        gate="strict",
        enabled=True,
        verified="2026-09-11",
        note="user verified: bulk SMS; SMS gateway; business messaging; regulation",
    ),
    CatalogEntry(
        id="textmagic-blog",
        url="https://www.textmagic.com/blog/feed/",
        kind="news",
        language="en",
        grade="A+",
        topic="SMS API; business texting; delivery; compliance; messaging",
        gate="strict",
        enabled=True,
        verified="2026-09-11",
        note="user verified: SMS API; business texting; delivery; compliance; messaging",
    ),
    CatalogEntry(
        id="textmarks",
        url="https://blog.textmarks.com/feed/",
        kind="news",
        language="en",
        grade="A+",
        topic="SMS marketing; short codes; text alerts; compliance",
        gate="strict",
        enabled=True,
        verified="2026-09-11",
        note="user verified: SMS marketing; short codes; text alerts; compliance",
    ),
    CatalogEntry(
        id="the-sms-works",
        url="https://thesmsworks.co.uk/blog/feed/",
        kind="news",
        language="en",
        grade="A+",
        topic="SMS API; delivery; pricing; sender IDs; UK SMS regulation",
        gate="strict",
        enabled=True,
        verified="2026-09-11",
        note="user verified: SMS API; delivery; pricing; sender IDs; UK SMS regulation",
    ),
    CatalogEntry(
        id="thundersms",
        url="https://thundersms.com/feed/",
        kind="news",
        language="en",
        grade="A+",
        topic="bulk SMS; SMS API; delivery; messaging business",
        gate="strict",
        enabled=True,
        verified="2026-09-11",
        note="user verified: bulk SMS; SMS API; delivery; messaging business",
    ),
    CatalogEntry(
        id="total-telecom",
        url="https://totaltele.com/feed/",
        kind="news",
        language="en",
        grade="A",
        topic="carriers; telecom deals; services; network business; regulation",
        gate="strict",
        enabled=True,
        verified="2026-09-11",
        note="user verified: carriers; telecom deals; services; network business; regulation",
    ),
    CatalogEntry(
        id="total-telecom-technology",
        url="https://totaltele.com/category/technology/feed/",
        kind="news",
        language="en",
        grade="A",
        topic="carrier technology; APIs; messaging infrastructure; services",
        gate="strict",
        enabled=True,
        verified="2026-09-11",
        note="user verified: carrier technology; APIs; messaging infrastructure; services",
    ),
    CatalogEntry(
        id="trumpia",
        url="https://blog.trumpia.com/rss.xml",
        kind="news",
        language="en",
        grade="A+",
        topic="SMS; MMS; text marketing; automation; compliance",
        gate="strict",
        enabled=True,
        verified="2026-09-11",
        note="user verified: SMS; MMS; text marketing; automation; compliance",
    ),
    CatalogEntry(
        id="zimperium",
        url="https://zimperium.com/blog/rss.xml",
        kind="news",
        language="en",
        grade="A",
        topic="smishing; mobile threats; phishing; mobile app security",
        gate="strict",
        enabled=True,
        verified="2026-09-11",
        note="user verified: smishing; mobile threats; phishing; mobile app security",
    ),
    CatalogEntry(
        id="14ip-status",
        url="https://status.14ip.com/history.rss",
        kind="status",
        language="en",
        grade="A+",
        topic="SMS API; SIP; telecom; delivery; incidents",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: SMS API; SIP; telecom; delivery; incidents",
    ),
    CatalogEntry(
        id="2bm-sms-status",
        url="https://2bm.statuspage.io/history.rss",
        kind="status",
        language="en",
        grade="A+",
        topic="send/receive SMS; Email-to-SMS; Danish network operators",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: send/receive SMS; Email-to-SMS; Danish network operators",
    ),
    CatalogEntry(
        id="5c-sms-status",
        url="https://5centsms.statuspage.io/history.rss",
        kind="status",
        language="en",
        grade="A+",
        topic="SMS queues; network providers; API; delivery infrastructure",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: SMS queues; network providers; API; delivery infrastructure",
    ),
    CatalogEntry(
        id="accent-status",
        url="https://status.accentvoice.com/history.rss",
        kind="status",
        language="en",
        grade="A+",
        topic="SMS Gateway; SMS API; UCaaS; telecom; incidents",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: SMS Gateway; SMS API; UCaaS; telecom; incidents",
    ),
    CatalogEntry(
        id="access4-status",
        url="https://status.access4.com/history.rss",
        kind="status",
        language="en",
        grade="A",
        topic="telecom platform; SMS Gateway; service availability",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: telecom platform; SMS Gateway; service availability",
    ),
    CatalogEntry(
        id="answerfirst-status",
        url="https://answerfirst.statuspage.io/history.rss",
        kind="status",
        language="en",
        grade="A",
        topic="SMS services; communications; delivery; incidents",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: SMS services; communications; delivery; incidents",
    ),
    CatalogEntry(
        id="apalo-status",
        url="https://apalo.statuspage.io/history.rss",
        kind="status",
        language="en",
        grade="A",
        topic="telecom; SMS/mobile data; APIs; mobile services",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: telecom; SMS/mobile data; APIs; mobile services",
    ),
    CatalogEntry(
        id="bandwidth-status",
        url="https://status.bandwidth.com/history.rss",
        kind="status",
        language="en",
        grade="A+",
        topic="A2P messaging; SMPP; SMS/MMS; toll-free; DLR; carriers",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: A2P messaging; SMPP; SMS/MMS; toll-free; DLR; carriers",
    ),
    CatalogEntry(
        id="bird-status",
        url="https://status.bird.com/history.rss",
        kind="status",
        language="en",
        grade="A+",
        topic="messaging platform; SMS; omnichannel; delivery incidents",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: messaging platform; SMS; omnichannel; delivery incidents",
    ),
    CatalogEntry(
        id="broadvoice-status",
        url="https://status.broadvoice.com/history.rss",
        kind="status",
        language="en",
        grade="A+",
        topic="SMS; SIP; carrier services; contact center; incidents",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: SMS; SIP; carrier services; contact center; incidents",
    ),
    CatalogEntry(
        id="clicksend-status",
        url="https://status.clicksend.com/history.rss",
        kind="status",
        language="en",
        grade="A+",
        topic="SMS; SMPP; HTTP/REST API; Email-to-SMS; global carriers",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: SMS; SMPP; HTTP/REST API; Email-to-SMS; global carriers",
    ),
    CatalogEntry(
        id="cm-com-status",
        url="https://status.cm.com/history.rss",
        kind="status",
        language="en",
        grade="A+",
        topic="CPaaS; messaging; SMS; channels; service incidents",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: CPaaS; messaging; SMS; channels; service incidents",
    ),
    CatalogEntry(
        id="commio-status",
        url="https://status.commio.com/history.rss",
        kind="status",
        language="en",
        grade="A+",
        topic="SMS/MMS; carrier platform; toll-free; international messaging",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: SMS/MMS; carrier platform; toll-free; international messaging",
    ),
    CatalogEntry(
        id="commpeak-status",
        url="https://www.commpeakstatus.com/history.rss",
        kind="status",
        language="en",
        grade="A+",
        topic="SMS/voice connectivity; carrier routes; multi-channel services",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: SMS/voice connectivity; carrier routes; multi-channel services",
    ),
    CatalogEntry(
        id="crm-messaging-status",
        url="https://crm-messaging.statuspage.io/history.rss",
        kind="status",
        language="en",
        grade="A+",
        topic="SMS; WhatsApp; Twilio/Vonage SMS APIs; inbound/outbound messaging",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: SMS; WhatsApp; Twilio/Vonage SMS APIs; inbound/outbound messaging",
    ),
    CatalogEntry(
        id="exceed-telecom-status",
        url="https://exceedtelecom.statuspage.io/history.rss",
        kind="status",
        language="en",
        grade="A",
        topic="carrier/UC platform; SMS/MMS; network operations",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: carrier/UC platform; SMS/MMS; network operations",
    ),
    CatalogEntry(
        id="flowroute-status",
        url="https://status.flowroute.com/history.rss",
        kind="status",
        language="en",
        grade="A+",
        topic="Inbound SMS; outbound SMS; MMS; APIs; carrier delivery",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: Inbound SMS; outbound SMS; MMS; APIs; carrier delivery",
    ),
    CatalogEntry(
        id="gatewayapi-status",
        url="https://status.gatewayapi.com/history.rss",
        kind="status",
        language="en",
        grade="A+",
        topic="SMS gateway; SMPP/API; MT/MO; DLR; carrier routing",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: SMS gateway; SMPP/API; MT/MO; DLR; carrier routing",
    ),
    CatalogEntry(
        id="goto-connect-status",
        url="https://status.goto.com/history.rss",
        kind="status",
        language="en",
        grade="A",
        topic="SMS; campaigns; business communications; messaging; incidents",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: SMS; campaigns; business communications; messaging; incidents",
    ),
    CatalogEntry(
        id="granite-my-granite-cloud-status",
        url="https://mygranitecloud.statuspage.io/history.rss",
        kind="status",
        language="en",
        grade="A",
        topic="SMS/MMS; UCaaS; telecom; incidents",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: SMS/MMS; UCaaS; telecom; incidents",
    ),
    CatalogEntry(
        id="hid-authentication-service-status",
        url="https://status.auth.hidglobal.com/history.rss",
        kind="status",
        language="en",
        grade="A",
        topic="SMS Gateway; OTP; authentication; fraud/security; regional availability",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: SMS Gateway; OTP; authentication; fraud/security; regional "
        "availability",
    ),
    CatalogEntry(
        id="hushed-status",
        url="https://status.hushed.com/history.rss",
        kind="status",
        language="en",
        grade="A",
        topic="P2P SMS; inbound SMS; outbound SMS; MMS; virtual numbers",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: P2P SMS; inbound SMS; outbound SMS; MMS; virtual numbers",
    ),
    CatalogEntry(
        id="infobip-status",
        url="https://status.infobip.com/history.rss",
        kind="status",
        language="en",
        grade="A+",
        topic="CPaaS; SMS; messaging channels; regional service health",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: CPaaS; SMS; messaging channels; regional service health",
    ),
    CatalogEntry(
        id="ixica-status",
        url="https://ixica.statuspage.io/history.rss",
        kind="status",
        language="en",
        grade="A+",
        topic="inbound/outbound SMS; traffic termination; carrier connectivity",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: inbound/outbound SMS; traffic termination; carrier connectivity",
    ),
    CatalogEntry(
        id="justcall-status",
        url="https://status.justcall.io/history.rss",
        kind="status",
        language="en",
        grade="A",
        topic="SMS; MMS; SIP; API; business messaging",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: SMS; MMS; SIP; API; business messaging",
    ),
    CatalogEntry(
        id="kaleyra-status",
        url="https://status.kaleyra.com/history.rss",
        kind="status",
        language="en",
        grade="A+",
        topic="SMS services; incoming/outgoing; international messaging; SMPP",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: SMS services; incoming/outgoing; international messaging; SMPP",
    ),
    CatalogEntry(
        id="laminin-status",
        url="https://laminin.statuspage.io/history.rss",
        kind="status",
        language="en",
        grade="A",
        topic="SMS; WhatsApp; telephony; communications platform health",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: SMS; WhatsApp; telephony; communications platform health",
    ),
    CatalogEntry(
        id="link-mobility-status",
        url="https://status.linkmobility.com/history.rss",
        kind="status",
        language="en",
        grade="A+",
        topic="enterprise messaging; SMS delivery; operators; regional incidents",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: enterprise messaging; SMS delivery; operators; regional incidents",
    ),
    CatalogEntry(
        id="lucid-communications-status",
        url="https://lucidone.statuspage.io/history.rss",
        kind="status",
        language="en",
        grade="A",
        topic="telecom provider; inbound/outbound SMS/MMS; SIP; service health",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: telecom provider; inbound/outbound SMS/MMS; SIP; service health",
    ),
    CatalogEntry(
        id="messente-status",
        url="https://status.messente.com/history.rss",
        kind="status",
        language="en",
        grade="A+",
        topic="SMS API; SMPP; inbound SMS; delivery reports; 2FA",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: SMS API; SMPP; inbound SMS; delivery reports; 2FA",
    ),
    CatalogEntry(
        id="next-identity-status",
        url="https://status.nextidentity.io/history.rss",
        kind="status",
        language="en",
        grade="A",
        topic="SMS API; identity; authentication; delivery",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: SMS API; identity; authentication; delivery",
    ),
    CatalogEntry(
        id="nxtl-mobile-status",
        url="https://nxtlmobile1.statuspage.io/history.rss",
        kind="status",
        language="en",
        grade="A",
        topic="mobile operator/services; SMS; eSIM; APIs",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: mobile operator/services; SMS; eSIM; APIs",
    ),
    CatalogEntry(
        id="optus-sms-suite-status",
        url="https://optus.statuspage.io/history.rss",
        kind="status",
        language="en",
        grade="A+",
        topic="operator SMS suite; messaging API; Email2SMS; mobile operators",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: operator SMS suite; messaging API; Email2SMS; mobile operators",
    ),
    CatalogEntry(
        id="plivo-status",
        url="https://status.plivo.com/history.rss",
        kind="status",
        language="en",
        grade="A+",
        topic="SMS API; messaging; delivery; carriers; incidents",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: SMS API; messaging; delivery; carriers; incidents",
    ),
    CatalogEntry(
        id="proximus-enco-status",
        url="https://enco.statuspage.io/history.rss",
        kind="status",
        language="en",
        grade="A+",
        topic="carrier SMS API; telecom API platform",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: carrier SMS API; telecom API platform",
    ),
    CatalogEntry(
        id="questline-status",
        url="https://status.questline.com/history.rss",
        kind="status",
        language="en",
        grade="A",
        topic="Outbound SMS; campaigns; API; engagement",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: Outbound SMS; campaigns; API; engagement",
    ),
    CatalogEntry(
        id="regal-ai-status",
        url="https://regal.statuspage.io/history.rss",
        kind="status",
        language="en",
        grade="A+",
        topic="SMS campaigns; carrier dependencies; Twilio SMS; A2P engagement",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: SMS campaigns; carrier dependencies; Twilio SMS; A2P engagement",
    ),
    CatalogEntry(
        id="saddleback-communications-status",
        url="https://status.saddlebackcomm.com/history.rss",
        kind="status",
        language="en",
        grade="A+",
        topic="Business SMS; SMS/MMS; carriers; routing; incidents",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: Business SMS; SMS/MMS; carriers; routing; incidents",
    ),
    CatalogEntry(
        id="servcomm-status",
        url="https://servcomm1.statuspage.io/history.rss",
        kind="status",
        language="en",
        grade="A",
        topic="telecom services; SMS/MMS messaging; SIP; platform incidents",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: telecom services; SMS/MMS messaging; SIP; platform incidents",
    ),
    CatalogEntry(
        id="seven-io-status",
        url="https://status.seven.io/history.rss",
        kind="status",
        language="en",
        grade="A+",
        topic="SMS Gateway; delivery; Messaging; API latency; incidents",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: SMS Gateway; delivery; Messaging; API latency; incidents",
    ),
    CatalogEntry(
        id="simbase-status",
        url="https://simbase.statuspage.io/history.rss",
        kind="status",
        language="en",
        grade="A",
        topic="IoT/mobile carrier connectivity; SMS Messaging; carrier provisioning",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: IoT/mobile carrier connectivity; SMS Messaging; carrier provisioning",
    ),
    CatalogEntry(
        id="simpletexting-status",
        url="https://status.simpletexting.com/history.rss",
        kind="status",
        language="en",
        grade="A+",
        topic="incoming/outgoing SMS/MMS; carrier incidents; 2FA delivery",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: incoming/outgoing SMS/MMS; carrier incidents; 2FA delivery",
    ),
    CatalogEntry(
        id="sinch-global-status",
        url="https://status.sinch.com/history.rss",
        kind="status",
        language="en",
        grade="A+",
        topic="SMS; messaging APIs; carrier incidents; delivery; regional outages",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: SMS; messaging APIs; carrier incidents; delivery; regional outages",
    ),
    CatalogEntry(
        id="sinch-wavy-latam-status",
        url="https://wavyglobal.statuspage.io/history.rss",
        kind="status",
        language="en",
        grade="A+",
        topic="SMPP; MT/MO; DLR; carrier delivery; LATAM mobile operators; WhatsApp",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: SMPP; MT/MO; DLR; carrier delivery; LATAM mobile operators; WhatsApp",
    ),
    CatalogEntry(
        id="smsportal-status",
        url="https://status.smsportal.com/history.rss",
        kind="status",
        language="en",
        grade="A+",
        topic="SMPP; REST; Email-to-SMS; inbound/outbound SMS; regions",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: SMPP; REST; Email-to-SMS; inbound/outbound SMS; regions",
    ),
    CatalogEntry(
        id="smtp2go-status",
        url="https://45hj7q5l4w10.statuspage.io/history.rss",
        kind="status",
        language="en",
        grade="A",
        topic="SMS messaging; delivery; API; incidents",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: SMS messaging; delivery; API; incidents",
    ),
    CatalogEntry(
        id="spruce-health-status",
        url="https://status.sprucehealth.com/history.rss",
        kind="status",
        language="en",
        grade="A",
        topic="SMS routing; delivery; communications platform; incidents",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: SMS routing; delivery; communications platform; incidents",
    ),
    CatalogEntry(
        id="suresms-status",
        url="https://suresms.statuspage.io/history.rss",
        kind="status",
        language="en",
        grade="A+",
        topic="SMPP; REST API; message services; SMS platform",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: SMPP; REST API; message services; SMS platform",
    ),
    CatalogEntry(
        id="telair-status",
        url="https://telairnet.statuspage.io/history.rss",
        kind="status",
        language="en",
        grade="A+",
        topic="SMS/MMS; telecom; delivery; incidents",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: SMS/MMS; telecom; delivery; incidents",
    ),
    CatalogEntry(
        id="telesign-status",
        url="https://status.telesign.com/history.rss",
        kind="status",
        language="en",
        grade="A+",
        topic="SMS Verify; Messaging API; identity; carrier/security services",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: SMS Verify; Messaging API; identity; carrier/security services",
    ),
    CatalogEntry(
        id="telnyx-status",
        url="https://status.telnyx.com/history.rss",
        kind="status",
        language="en",
        grade="A+",
        topic="SMS/MMS; messaging API; deliverability; 10DLC; carrier connectivity",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: SMS/MMS; messaging API; deliverability; 10DLC; carrier connectivity",
    ),
    CatalogEntry(
        id="textline-status",
        url="https://status.textline.com/history.rss",
        kind="status",
        language="en",
        grade="A+",
        topic="business SMS/MMS; carrier layer; 10DLC; delivery",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: business SMS/MMS; carrier layer; 10DLC; delivery",
    ),
    CatalogEntry(
        id="textmagic-status",
        url="https://status.textmagic.com/history.rss",
        kind="status",
        language="en",
        grade="A+",
        topic="outbound/inbound SMS; Email-to-SMS; SMS API Gateway",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: outbound/inbound SMS; Email-to-SMS; SMS API Gateway",
    ),
    CatalogEntry(
        id="transmitsms-status",
        url="https://status.transmitsms.com/history.rss",
        kind="status",
        language="en",
        grade="A+",
        topic="MT/MO; wholesale SMS; DLR; Email-to-SMS; regional connectivity",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: MT/MO; wholesale SMS; DLR; Email-to-SMS; regional connectivity",
    ),
    CatalogEntry(
        id="transponder-status",
        url="https://status.transponder.no/history.rss",
        kind="status",
        language="en",
        grade="A",
        topic="SMS Gateway; SMS delivery; API; incidents",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: SMS Gateway; SMS delivery; API; incidents",
    ),
    CatalogEntry(
        id="tsg-global-status",
        url="https://status.tsgglobal.com/history.rss",
        kind="status",
        language="en",
        grade="A+",
        topic="messaging services; SMPP; local/toll-free SMS/MMS; upstream MNOs",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: messaging services; SMPP; local/toll-free SMS/MMS; upstream MNOs",
    ),
    CatalogEntry(
        id="twilio-status",
        url="https://status.twilio.com/history.rss",
        kind="status",
        language="en",
        grade="A+",
        topic="SMS; MMS; SMPP; RCS; Messaging Services; carriers; delivery incidents",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: SMS; MMS; SMPP; RCS; Messaging Services; carriers; delivery incidents",
    ),
    CatalogEntry(
        id="vonage-api-status",
        url="https://vonageapi.statuspage.io/history.rss",
        kind="status",
        language="en",
        grade="A+",
        topic="SMS; MMS; SMPP; short codes; 10DLC; Messages API; carrier incidents",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: SMS; MMS; SMPP; short codes; 10DLC; Messages API; carrier incidents",
    ),
    CatalogEntry(
        id="xmatters-status",
        url="https://xmatters.statuspage.io/history.rss",
        kind="status",
        language="en",
        grade="A",
        topic="SMS notifications; delivery; enterprise messaging; incidents",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: SMS notifications; delivery; enterprise messaging; incidents",
    ),
    CatalogEntry(
        id="ziron-status",
        url="https://www.zironstatus.com/history.rss",
        kind="status",
        language="en",
        grade="A+",
        topic="Inbound SMS; outbound SMS; API; number portability; telecom",
        gate="strict",
        enabled=False,
        verified="2026-09-11",
        note="user verified: Inbound SMS; outbound SMS; API; number portability; telecom",
    ),
)


def catalog_issues(entries: tuple[CatalogEntry, ...] | list[CatalogEntry] = CATALOG) -> list[str]:
    """Вернуть список проблем каталога (пустой список = всё в порядке).

    Проверяются уникальность ``id`` и ``url``, допустимость ``kind``/``gate``
    и схема URL. Используется тестом и командой ``sources``.
    """
    issues: list[str] = []
    seen_ids: set[str] = set()
    seen_urls: set[str] = set()
    for entry in entries:
        if entry.kind not in KINDS:
            issues.append(f"{entry.id}: unknown kind {entry.kind!r}")
        if entry.gate not in ("strict", "llm"):
            issues.append(f"{entry.id}: unknown gate {entry.gate!r}")
        if not entry.url.startswith(("http://", "https://")):
            issues.append(f"{entry.id}: url must be http(s): {entry.url!r}")
        if entry.id in seen_ids:
            issues.append(f"duplicate id: {entry.id}")
        if entry.url in seen_urls:
            issues.append(f"duplicate url: {entry.url}")
        seen_ids.add(entry.id)
        seen_urls.add(entry.url)
    return issues


def catalog_counts(
    entries: tuple[CatalogEntry, ...] | list[CatalogEntry] = CATALOG,
) -> dict[str, dict[str, int]]:
    """Счётчики каталога по видам, языкам и классам (для ``sources``)."""
    counts: dict[str, dict[str, int]] = {"kind": {}, "language": {}, "grade": {}, "enabled": {}}
    for entry in entries:
        counts["kind"][entry.kind] = counts["kind"].get(entry.kind, 0) + 1
        counts["language"][entry.language] = counts["language"].get(entry.language, 0) + 1
        counts["grade"][entry.grade] = counts["grade"].get(entry.grade, 0) + 1
        state = "enabled" if entry.enabled else "disabled"
        counts["enabled"][state] = counts["enabled"].get(state, 0) + 1
    return counts
